# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "main", primary: true do |main|
    main.vm.box = "ZaitsevSergey/ansible"
    main.vm.network "forwarded_port", guest: 80, host: 8090, autocorrect: true
    main.vm.network "private_network", ip: "192.168.77.10"
    main.vm.synced_folder ".", "/home/vagrant/shared"
    main.ssh.insert_key = false
    main.vm.provider :virtualbox do |vb|
        vb.name = "master"
        vb.memory = "1024"
        vb.customize ["modifyvm", :id, 
                      "--uartmode1", "disconnected",
                      "--cpus", "2"]
    end
  end
  config.vm.define "slave1" do |slave1|
    slave1.vm.box = "ZaitsevSergey/ansible"
    slave1.vm.network "forwarded_port", guest: 80, host: 8091, autocorrect: true
    slave1.vm.network "private_network", ip: "192.168.77.11"
    slave1.vm.synced_folder ".", "/mnt/host_machine"
    slave1.ssh.insert_key = false
    slave1.vm.provider :virtualbox do |vb|
        vb.name = "slave1"
        vb.memory = "512"
        vb.customize ["modifyvm", :id, 
                      "--uartmode1", "disconnected",
                      "--cpus", "2"]
    end
  end
  config.vm.define "slave2" do |slave2|
    slave2.vm.box = "ZaitsevSergey/ansible"
    slave2.vm.network "forwarded_port", guest: 80, host: 8092, autocorrect: true
    slave2.vm.network "private_network", ip: "192.168.77.12"
    slave2.vm.synced_folder ".", "/mnt/host_machine"
    slave2.ssh.insert_key = false
    slave2.vm.provider :virtualbox do |vb|
        vb.name = "slave2"
        vb.memory = "512"
        vb.customize ["modifyvm", :id, 
                      "--uartmode1", "disconnected",
                      "--cpus", "2"]
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
